-- Phase 4-01: adds insulin_score smallint column to ai_daily_targets
-- Stores the 0-100 Insulin Balance score as a queryable integer (separate from
-- insulin_score_basis jsonb which stores { key_factors: string[] }).
-- Using smallint: valid range 0-100 fits comfortably; saves storage vs. integer.

alter table public.ai_daily_targets
  add column insulin_score smallint
  check (insulin_score >= 0 and insulin_score <= 100);

comment on column public.ai_daily_targets.insulin_score is
  '0–100 Insulin Balance score generated by Claude. Higher = better insulin balance potential for this profile. 0–40: high risk; 41–70: moderate; 71–100: optimised.';
